version: 2
jobs:
  build:
    environment:
      REPO_NAME: "wastrachan"
      IMAGE_NAME: "arin-waitlist"
      IMAGE_VERSION: "1.1"
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install deps
          command: |
            apk --no-cache add curl
      - run:
          name: Build image
          command: |
            docker build -t $IMAGE_NAME .
            docker tag $IMAGE_NAME $REPO_NAME/$IMAGE_NAME:latest
            docker tag $IMAGE_NAME $REPO_NAME/$IMAGE_NAME:$IMAGE_VERSION
      - deploy:
          name: Publish image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push $REPO_NAME/$IMAGE_NAME:latest
              docker push $REPO_NAME/$IMAGE_NAME:$IMAGE_VERSION
            fi

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only: master
